#Start code here
from turtle import *
turtle = Turtle()
screen = Screen()
screen.bgcolor(255, 240, 240)
turtle.color(255)
turtle.width(5)
turtle.penup()
turtle.goto(0, 0)
turtle.pendown()
def curved_box(sides, size):
  for i in range(sides):
    turtle.circle(size,extent=90)
    turtle.forward(size+60)
  turtle.circle(size,extent=90)
def snake(colour, size):
  turtle.color(255, 255, 255)
  turtle.fillcolor(colour)
  turtle.begin_fill()
  turtle.forward(32*size)
  curved_box(2, 45*size)
  turtle.forward(22*size)
  turtle.left(90)
  turtle.forward(60*size)
  turtle.right(90)
  turtle.forward(8*size)
  turtle.right(90)
  turtle.forward(102*size)
  curved_box(1, 45*size)
  turtle.forward(22*size)
  turtle.left(90)
  turtle.forward(30*size)
  turtle.circle(-45*size,extent=90)
  turtle.forward(32*size)
  turtle.backward(32*size)
  turtle.end_fill()
  turtle.forward(170*size)
  turtle.backward(140*size)
  #eye # your own code
  turtle.penup()
  turtle.backward(23*size)
  turtle.left(90)
  turtle.forward(250*size)
  turtle.dot(24 * size,'white') # your own code
  turtle.backward(250*size)
  turtle.right(90)
  turtle.forward(33*size)
  turtle.pendown()
snake('#3774A8', 0.4)
turtle.setheading(180)
snake('#F6D646', 0.4)
